[package]
name = "rosu-pp"
version = "0.1.1"
authors = ["MaxOhn <ohn.m@hotmail.de>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository = "https://github.com/MaxOhn/rosu-pp"
documentation = "https://docs.rs/rosu-pp/"
description = "osu! difficulty and pp calculation for all modes"
keywords = ["osu", "pp", "stars", "async", "async-std"]

[features]
default = ["osu", "taiko", "fruits", "mania", "no_leniency", "async_std"]

osu = []
taiko = []
fruits = []
mania = []

all_included = []
no_leniency = []
no_sliders_no_leniency = []
async_std = ["async-std"]

[dependencies]
async-std = { version = "1.9.0", optional = true }
